#开发者：罗地观生
#开发时间：2021/4/18 18:03
'''元组的创建方式'''
'''第一种，使用()'''
t=('python','made','me','brazy')
print(type(t))
print(t)
t2='python','made','me',98#省略括号
print(type(t2))
print(t2)

t3='hdsufh',#只有一个元素必须末尾加逗号
print(type(t3))
print(t3)
'''第二种,使用内置tuple函数'''
t1=tuple(('python','made','this'))
print(type(t1))
print(t1)
'''空列表的创建'''
lst=[]
lst1=list()
'''空字典的创建'''
d={}
d1=dict()
'''空元组的创建'''
t4=()
t5=tuple()
print('空列表',lst,lst1)
print('空字典',d,d1)
print('空元组',t4,t5)
